services:

  apisix:
    image: apache/apisix:${APISIX_VERSION}
    restart: always
    user: root
    environment:
      APISIX_STAND_ALONE: "true"
    volumes:
      - ${PWD}/apisix.yaml:/usr/local/apisix/conf/apisix.yaml
      - ${PWD}/config.yaml:/usr/local/apisix/conf/config.yaml
    ports:
      # Web - Proxy
      - 9080:9080

  device:
    image: nginx:${NGINX_VERSION}
    restart: always
    configs:
      - source: device.html
        target: /usr/share/nginx/html/index.html
      - source: default.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 80

  home:
    image: nginx:${NGINX_VERSION}
    restart: always
    configs:
      - source: home.html
        target: /usr/share/nginx/html/index.html
      - source: default.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 80

configs:
  device.html:
    content: |
      <!doctype html>
      <html>
        <head>
          <title>Hello Device.</title>
          <meta charset="utf-8" />
        </head>
        <body>
          <h1>
            I am a Device!
          </h1>
        </body>
      </html>
  home.html:
    content: |
      <!doctype html>
      <html>
        <head>
          <title>Hello Home</title>
          <meta charset="utf-8" />
        </head>
        <body>
          <h1>
            This is Customer Home.
          </h1>
        </body>
      </html>
  default.conf:
    content: |
      server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
          try_files $$uri $$uri/ /index.html;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
          root   /usr/share/nginx/html;
        }
      }
